
version: '3'
services:
        web:
                image: flask_fnafmovie_v1
                build: .
                ports:
                        - "2009:2009"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped