version: '3'
services:
        web:
                image: fnafmovie
                build: .
                ports:
                        - "2009:2009"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
